services:
  # ---------- MinIO ----------
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

  fix-data-perms:
    image: busybox:1.36
    user: "0:0"
    command: chown -R 50000:0 /opt/airflow/data
    volumes:
      - ./data:/opt/airflow/data
    restart: "no"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  airflow:
    build: .
    user: "${AIRFLOW_UID:-50000}:0"
    image: assignment-airflow:latest
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - _AIRFLOW_WWW_USER_USERNAME=${_AIRFLOW_WWW_USER_USERNAME}
      - _AIRFLOW_WWW_USER_PASSWORD=${_AIRFLOW_WWW_USER_PASSWORD}
      - PYTHONPATH=/opt/airflow/src
      - S3_ENDPOINT_URL=http://minio:9000
      - DB_PATH=/opt/airflow/data_db/commits.duckdb
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
      - ./data:/opt/airflow/data
      - ./data_db:/opt/airflow/data_db
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: .
    user: "${AIRFLOW_UID:-50000}:0"
    image: assignment-airflow:latest
    restart: always
    depends_on:
      - airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - PYTHONPATH=/opt/airflow/src
      - S3_ENDPOINT_URL=http://minio:9000
      - DB_PATH=/opt/airflow/data_db/commits.duckdb
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
      - ./data:/opt/airflow/data
      - ./data_db:/opt/airflow/data_db
    command: scheduler
